apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-stock-manager
spec:
  selector:
    matchLabels:
      app: svc-stock-manager
  replicas: 1
  template:
    metadata:
      labels:
        app: svc-stock-manager
    spec:
      containers:
        - name: svc-stock-manager
          image: evestidor/svc-stock-manager:master
