apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-price-simulator
spec:
  selector:
    matchLabels:
      app: stock-price-simulator
  replicas: 1
  template:
    metadata:
      labels:
        app: stock-price-simulator
    spec:
      containers:
        - name: stock-price-simulator
          image: evestidor/stock-price-simulator:master
