#!/bin/bash
set -e

# Getting image name & latest commit
ORGANIZATION_NAME=$(head -n 1 config/vars/organization_name)
PROJECT_NAME=$(head -n 1 config/vars/project_name)
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
LATEST_COMMIT=$(git rev-parse HEAD)
CLEANED_BRANCH_NAME=${BRANCH_NAME//\//-}  # Slashes can't go through
IMAGE_NAME=$ORGANIZATION_NAME/$PROJECT_NAME

# Building image
config/build-image

# Pushing image
docker push $IMAGE_NAME:$CLEANED_BRANCH_NAME
docker push $IMAGE_NAME:$CLEANED_BRANCH_NAME-$LATEST_COMMIT
